{
  "comments": [
    {
      "key": {
        "uuid": "874e4355_f2a8489e",
        "filename": "src/SharedMemory.cpp",
        "patchSetId": 2
      },
      "lineNbr": 115,
      "author": {
        "id": 1009284
      },
      "writtenOn": "2019-05-07T18:16:30Z",
      "side": 1,
      "message": "Not kosher.  Cannot throw exceptions in destructors.",
      "range": {
        "startLine": 115,
        "startChar": 15,
        "endLine": 115,
        "endChar": 33
      },
      "revId": "07ac7dc0beeea932ae631c2718e7cd6eb44af272",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "2d54eba9_1305719f",
        "filename": "src/SharedMemory.cpp",
        "patchSetId": 2
      },
      "lineNbr": 213,
      "author": {
        "id": 1009284
      },
      "writtenOn": "2019-05-07T18:16:30Z",
      "side": 1,
      "message": "Same as above.",
      "range": {
        "startLine": 212,
        "startChar": 12,
        "endLine": 213,
        "endChar": 55
      },
      "revId": "07ac7dc0beeea932ae631c2718e7cd6eb44af272",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    }
  ]
}