{
  "comments": [
    {
      "key": {
        "uuid": "1d3ea67c_1c33db72",
        "filename": "src/Exception.cpp",
        "patchSetId": 4
      },
      "lineNbr": 101,
      "author": {
        "id": 1009284
      },
      "writtenOn": "2019-10-15T16:59:34Z",
      "side": 1,
      "message": "Where is this defined?",
      "range": {
        "startLine": 101,
        "startChar": 57,
        "endLine": 101,
        "endChar": 60
      },
      "revId": "827babf7e593b1da046d1a06604027e225303aea",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    }
  ]
}